### ISSUE TITLE
README update - add parameter for status-left-length

### ISSUE THREAD

**Issue by kogent** [thewtex/tmux-mem-cpu-load#19]
Since the default `status-left-length` setting for tmux is `10` the supplied initial parameters in the `README` will cause tmux to partially show the memory metrics and nothing else.  It would make life easier for tmux n00b's trying out this project if the sample config lines included setting `status-left-length` to something large enough to display the full script output.  Since this is a max value setting and not a static setting, using a large value should be safe:
```
set -g status-interval 2
set -g status-left "#S #[fg=green,bg=black]#(tmux-mem-cpu-load --colors --interval 2)#[default]"
set -g status-left-length 60
```

**Comment by thewtex** [comment]
Great suggestion -- thanks!
