### ISSUE TITLE
I get The interval and graph lines options are now spe...

### ISSUE THREAD

**Issue by timhtheos** [thewtex/tmux-mem-cpu-load#24]
I have this yesterday, but I reformatted today.  I now get this:

```
The interval and graph lines options are now spe
```

**Comment by hadesgames** [comment]
If you are using https://github.com/tony/tmux-config see this pull request:

https://github.com/tony/tmux-config/pull/10

**Comment by l0ner** [comment]
There was a switch from positional to keyworded arguments around version 3.0.0. See `tmux-mem-cpu-load --help` or readme and adjust your tmux config accordingly.

**Comment by timhtheos** [comment]
@hadesgames @l0ner Thanks for the tip. I got my tmux.conf file updated and it works.  Got a good understanding too with --help.  Thanks.
