### ISSUE TITLE
tpm vs antigen

### ISSUE THREAD

**Issue by NHDaly** [thewtex/tmux-mem-cpu-load#41]
Hi! I'm just wondering, since this is at its heart a tmux feature, why do you suggest users install it with antigen?

Could it be installed through [tmux-plugins/tpm](https://github.com/tmux-plugins/tpm)? I guess it might have something to do with the complied aspect of it, but you could probably get that to work through tpm too.

I ask because it seems like it's not related to `zsh` at all, and shouldn't need `zsh` as a dependency. Is that true? :)

**Comment by thewtex** [comment]
Closing -- instructions for tpm installation have been added to the README.

**Comment by NHDaly** [comment]
oops, I think this was a dupe of #43 anyway. :) Thanks again.
