### ISSUE TITLE
Mac OSX: Every time I open a new window, it reinstalls tmux-mem-cpu-load

### ISSUE THREAD

**Issue by NHDaly** [thewtex/tmux-mem-cpu-load#42]
This has frustrated me for a while, but I finally know what's happening.

When I open a new window, it rebuilds and attempts to install the binary to my machine:

```
~/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-thewtex-SLASH-tmux-mem-cpu-load.git ~/dotfiles/nhdaly
-- Darwin detected
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/nhdaly/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-thewtex-SLASH-tmux-mem-cpu-load.git
[100%] Built target tmux-mem-cpu-load
Password:
[100%] Built target tmux-mem-cpu-load
Install the project...
-- Install configuration: "MinSizeRel"
-- Installing: /Users/nhdaly/homebrew/bin/tmux-mem-cpu-load
~/dotfiles/nhdaly
🍰 22:27:35  ~/dotfiles/nhdaly   master ✘ ✹ ✭ 
```

BUT, as you can see, I've realized it's putting it in `/Users/nhdaly/homebrew/bin/tmux-mem-cpu-load` for some magical reason. I assume this must be because I've installed `homebrew` to that directory, and it's probably finding the version of `cmake` installed by `homebrew`?

So ANYWAY, after it's installed, the `tmux-mem-cpu-load.plugin.zsh` script checks (on [this line](https://github.com/thewtex/tmux-mem-cpu-load/blob/master/tmux-mem-cpu-load.plugin.zsh#L18)) whether it's installed at `/usr/local/bin/tmux-mem-cpu-load`, which of course it isn't.

Can that line somehow inherit the same magic as `cmake` to figure out where to check for it? Thanks!

**Comment by NHDaly** [comment]
(This is also be fixed by installing through `tpm` as I've done in #44.) :)

**Comment by thewtex** [comment]
@NHDaly how about changing the test to:

```
if type tmux-mem-cpu-load
```
?

**Comment by NHDaly** [comment]
Sure, that sounds better to me! :) (I just learned about `type`; cool!)
