### ISSUE TITLE
tpm vs antigen

### ISSUE THREAD

**Issue by NHDaly** [thewtex/tmux-mem-cpu-load#43]
Hi! I'm just wondering, since this is at its heart a tmux feature, why do you suggest users install it with antigen?

Could it be installed through [tmux-plugins/tpm](https://github.com/tmux-plugins/tpm)? I guess it might have something to do with the compiled aspect of it, but you could probably get that to work through tpm too?

------- EDIT ------
Well, not really an edit, since I haven't submitted yet, but I spent about 20-30 min trying to set this up, and I see one issue that might've prevented you from doing it this way in the first place: as far as I can tell, through a tmux plugin you cannot get the user to type a password to authenticate make install... That might mean it's not gonna work for a tmux plugin.

**Comment by NHDaly** [comment]
Actually, after playing with it a bit more, I think it's possible! One way would be to just forgo the `make install` and call the binary directly from the plugin directory! This is also preferable since it doesn't require sudo. :) I'll send along a strawman PR now!

**Comment by thewtex** [comment]
Antigen or other means can be used to install tmux-mem-cpu-load -- I think many folks build from source directly. I will create another issue to document how to install with other package managers.

**Comment by NHDaly** [comment]
Yeah that makes sense. Thanks!
~Nathan

**Comment by thewtex** [comment]
@NHDaly issue can be closed? Also, could you please create a PR that adds your name to the list of contributors at the bottom of the README?

**Comment by NHDaly** [comment]
Yep, I think so! :) I just installed it on a new computer with no problems! :D It looks much nicer now. :)
https://github.com/NHDaly/nhdaly_dotfiles/blob/master/tmux.conf.nhdaly#L112

**Comment by NHDaly** [comment]
> Also, could you please create a PR that adds your name to the list of contributors at the bottom of the README?

And yeah, sure I can do that -- thanks so much! I didn't really contribute much. :)
