### ISSUE TITLE
Inverse coloring issue

### ISSUE THREAD

**Issue by mavam** [thewtex/tmux-mem-cpu-load#48]
I'm observing inverse coloring in the output on the latest macos Sierra. That is, for a list of 101 colors and produced color `x`, I am getting instead `101 - x`. Here's an example:

```
#[bg=default] #[fg=colour144]#[fg=black,bg=colour144] 9713/16384MB #[fg=colour52]#[fg=brightwhite,bg=colour52] [          ]  3.3% #[fg=colour16]#[fg=brightwhite,bg=colour16] 1.4 1.49 1.56
```

The CPU utilization is only 3.3%, but the display is bright white on red. I confirmed this intuition with this hack:

```diff
diff --git a/common/main.cc b/common/main.cc
index 2b237d8..9424a23 100644
--- a/common/main.cc
+++ b/common/main.cc
@@ -63,7 +63,7 @@ std::string cpu_string( CPU_MODE cpu_mode, unsigned int cpu_us
     oss.precision( 0 );
   }
 
-  unsigned int percent = static_cast<unsigned int>( percentage );
+  unsigned int percent = 101 - static_cast<unsigned int>( percentage );
   if( use_colors )
   {
     if( use_powerline_right )
```

After using this patch, the colors appear correct for CPU, but still not for memory and load averages. So this color inversion applies to all measurements. The percentage *value* is actually correct, but somehow the translation into colors is not working properly. Any ideas what's causing this?

**Comment by thewtex** [comment]
I checked on macOS 10.12.4, and I do not see this behavior.

Please try setting `CMAKE_BUILD_TYPE` to `Debug`, then stepping through with a debugger like *gdb* or *lldb* to figure out the source of the problem.

**Comment by mavam** [comment]
Just making sure I'm chasing a bug and not a feature: I've did another test on FreeBSD with similar results, which made me wonder: is black background and white foreground the default for values near 0? I'm noticing that the spectrum goes from black (0), to red, to yellow, to green, to white (100). Would you agree that it should be the opposite? That is, the color red should indicate full utilization, signaling potential performance problems while low utilization (green) should indicate that enough resources are available.

**Comment by thewtex** [comment]
Those are the expected colors.

We [use](https://github.com/thewtex/tmux-mem-cpu-load/blob/master/common/generate-luts.py) the *hot* [colormap](https://matplotlib.org/examples/color/colormaps_reference.html) for the CPU usage from matplotlib.

**Comment by mavam** [comment]
I understand that this was a design design, but don't you find this coloring scheme counter-intuitive?Usually, red signals errors and alerts, whereas green implies a healthy state.

I'd be happy to provide a pull request that adds the option to reverse the color scheme (e..g, by specifying `-r` on the command line).

**Comment by thewtex** [comment]
The color map does not go from red to green, as shown in the links provided.

There are different hues per metric, memory, CPU usage, and load. All colormaps are consistently white backgrounds on black text when maxed out.

**Comment by TheChymera** [comment]
I am having my own (possibly much more basic) issue with the color scheme, but I browsed everything color-related and came across this:

>  All colormaps are consistently white backgrounds on black text when maxed out.

I really think allowing users to set something else would be worthwhile. Particularly for people who use negative contrast (i.e. dark text on light backgrounds) black text on white is basically inconspicuous. High saturation is generally the best way to draw attention to elements which might require attention (and is contrast-independent).
