### ISSUE TITLE
Wont load, installed using tpm 

### ISSUE THREAD

**Issue by BlisteringSyko** [thewtex/tmux-mem-cpu-load#55]
Hello, 

Im sure im mising something simple here, but im just not seeing it. 
Installed tpm using the tpm install instructions.
$ git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

After prefix + I  the folder  tmux-mem-cpu-load  is created in ~/.tmux/plugins/ 

even after prefix + r  it does not load. 

Reading "If you installed using tpm, you must specify the full path to the tmux-mem-cpu-load script, like below:"  there is no script called "tmux-mem-cpu-load" in that folder, 

![image](https://user-images.githubusercontent.com/32125693/46878225-b8cc5e80-ce10-11e8-9267-ac1c48c10883.png)

 prefix + r
![image](https://user-images.githubusercontent.com/32125693/46878302-eb765700-ce10-11e8-8c05-c39931526143.png)

```
# Appearance customization
#set -g status-bg black
#set -g status-fg white
set -g window-status-current-fg red
set -g pane-active-border-fg red
set -g clock-mode-colour red

# Custom modifier key
set -g prefix C-Space
unbind-key C-b
bind-key C-Space send-prefix

# Terminal improvements
set -g terminal-overrides "xterm*:XT:smcup@:rmcup@"
set-window-option -g automatic-rename off
set-option -g set-titles on
set -g mouse on
set -g default-terminal screen-256color
set -g status-keys vi
set -g history-limit 10000

# Clear scrollback buffer
bind l clear-history

# Custom key bindings to split the window
bind-key v split-window -h
bind-key s split-window -v

# Reload tmux config
bind r source-file ~/.tmux.conf

# No delay for escape key press
set -sg escape-time 0

# Shift arrow to switch panes
bind -n S-Left  select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up    select-pane -U
bind -n S-Down  select-pane -D

# Control arrow to create panes
bind -n C-Down  split-window -v
bind -n C-Up    split-window -v -b
bind -n C-Right split-window -h
bind -n C-Left  split-window -h -b

# Easier window navigation
bind -n C-Tab     next-window
bind -n C-S-Tab   previous-window
bind -n C-S-Left  previous-window
bind -n C-S-Right next-window

# Ctrl + Alt + Left/Right to move windows
bind-key -n C-M-Left swap-window -t -1
bind-key -n C-M-Right swap-window -t +1

# Copy to cygwin clipboard
bind -n C-t run "tmux save-buffer - > /dev/clipboard"

# Kill tabs quicker
bind-key x kill-pane

set -g terminal-overrides "xterm*:kLFT5=\eOD:kRIT5=\eOC:kUP5=\eOA:kDN5=\eOB:smkx@:rmkx@"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'thewtex/tmux-mem-cpu-load'


set -g status-interval 2
set -g status-right '#[fg=green]#($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --colors --powerline-right --interval 2)#[default]'
set -g status-right-length 60

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

**Comment by BlisteringSyko** [comment]
i ended up building this manually, tpm still wouldnt load it.
so i installed it to the system which works and got rid of tpm.

If there are missing parts from how to use it with tpm please update the instructions, or make them more clear.

Thanks.

**Comment by l0ner** [comment]
Given the dir listing it seems tpm pulls the source code without compiling it. 

@thewtex in `tmux-mem-cpu-load.plugin.tmux`:

```bash
if output=$(cmake . 2>&1); then 
    tmux run-shell "echo \"'cmake $CURRENT_DIR' failed.
    $output
    \""; 
else 
    exit 1; 
fi
````
exit 1 in the else statement will exit from the script, essentially aborting it before it can actually compile the code.

incriminated commit is 26b53ea94bd1890020875eaa040b5fbb845b8cb1 as || && chains doesn't translate directly (or rather, like this) into if-then-else.

`exit 1` should be put inside the if statement and else removed completely.

the same goes for the build step.

**Comment by mguthaus** [comment]
It did this for me when cmake was not installed. I also went in and manually did "cmake .; make" in the plugin dir.

**Comment by thewtex** [comment]
Patches welcome to improve the behavior here :1234:

**Comment by rbreaves** [comment]
Just to note, had to run this and yea run cmake in the dir after tpm.

sudo apt-get install cmake build-essential

**Comment by buzurgmekhr** [comment]
the same issue 🙁
