### ISSUE TITLE
Provide usage metric variables individually

### ISSUE THREAD

**Issue by rwev** [thewtex/tmux-mem-cpu-load#59]
Other tmux status-line plugins provide variables that can be accessed individually, e.g. 
```bash
set -g @plugin 'tmux-plugins/tmux-cpu'
``` 
provides access to 
```bash
set -g status-right '#{cpu_bg_color} CPU: #{cpu_icon} #{cpu_percentage}'
```
I really like what tmux-mem-cpu-load provides, but I don't want to always use the entire string,
```
2885/7987MB [ | | | | |     ]  51.2% 2.11 2.35 2.44
```
all the time. 

Partitioning the output into individual variables would vastly improve the ability to integrate the plugin into custom status lines, and eliminate bloat and overcrowding, particularly on small laptop screens, or when using a large font.

**Comment by thewtex** [comment]
:+1:
