### ISSUE TITLE
Provide argument flag to disable coloration based on usage

### ISSUE THREAD

**Issue by bcaradima** [thewtex/tmux-mem-cpu-load#63]
I've just managed to get your cool plugin working with `tpm`, many thanks! I'm just wondering if there is an existing argument to disable the coloration of the CPU usage bar graph (and maybe other UI elements) based on usage? I didn't find such an argument in the `man` page but it would be nice to have.

**Comment by thewtex** [comment]
@bcaradima thanks for the feedback -- glad you find it useful :-)

There should be no color by default: `tmux-mem-cpu-load`. Colors can be enabled by passing the `--colors` flag, e.g. `tmux-mem-cpu-load --colors`.
