### ISSUE TITLE
Fixed decimal points

### ISSUE THREAD

**Issue by topaxi** [thewtex/tmux-mem-cpu-load#66]
The UI can be quite jumpy at times, it would be great if there was an option to make cpu percentage and load numbers having a fixed amount of decimal points.

Expected:

```
| 20.0% 1.20 1.01 1.00 |
```

Or alternatively pad the output with whitespaces.

```
| 20%   1.2  1.01 1    |
```

Actual:

```
| 20% 1.2 1.01 1 |
```

**Comment by thewtex** [comment]
A few improvements in #69

**Comment by topaxi** [comment]
Very nice, thank you :heart:
