### ISSUE TITLE
empty cpu usage bar graph

### ISSUE THREAD

**Issue by gatoravi** [thewtex/tmux-mem-cpu-load#7]
I just installed tmux-mem-cpu-load on Ubuntu lucid. I'm using tmux1.5 on iterm 0.10 (sshing  into Ubuntu from my Mac) 

The CPU usage bar graph shows up empty for me and I also see a number 0 to the left of my memory usage. Any idea what this might be due to ?
![screen shot 2014-03-19 at 5 07 26 pm](https://f.cloud.github.com/assets/764948/2466712/7633156c-afb3-11e3-9df6-6f4b7d05287c.png)

**Comment by nxjosephofficial** [comment]
Is there a way to remove that '0'? I didn't have it before i installed this plugin.

```
# Some tweaks to the status line
set -g status-interval 1
set -g status-right "#S #(tmux-mem-cpu-load --interval 1)#[default]"
set -g status-right-length 60
set -g window-status-current-style "bold"
```
