### ISSUE TITLE
disable date and time

### ISSUE THREAD

**Issue by sandikata** [thewtex/tmux-mem-cpu-load#84]
Hello,

Is it possible for this plugin to be disabled date and time in status bar?

**Comment by thewtex** [comment]
Date and time can be provided with tmux settings, e.g.

```
set -g status-right "#{prefix_highlight} #H %I:%M%P %a %m/%d"
```

results in:

![image](https://user-images.githubusercontent.com/25432/209214641-fb470b61-8331-4d9f-86b3-249f6bc15d7e.png)
