### ISSUE TITLE
Can I somehow adjust the colors?

### ISSUE THREAD

**Issue by TheChymera** [thewtex/tmux-mem-cpu-load#85]
Plainly, the colors are illegible, in particular for the memory usage:
![decohost_2022-12-14T03:19:35](https://user-images.githubusercontent.com/950524/207543133-19b1f870-f4b9-4400-8f75-f7f87bb8722b.png)

I know they can be disabled, but they're actually super-useful, just that they also prevent me from reading the text after I have been alerted to the fact that things are happening.

Would it be possible to customize them somehow?
I know too many config options actually make things more confusing but the alternative as it stands is having dark green (? can't even tell) on dark blue.

**Comment by TheChymera** [comment]
Also, when `--color` is passed, any previously defined colors get overriden. I understand this much is probably desired and obvious, just that the README example combines the two, so I had been hoping I can adjust this somehow:

```
set -g status-left "#S #[fg=green,bg=black]#(tmux-mem-cpu-load --colors --interval 2)#[default]"
```

**Comment by thewtex** [comment]
Maybe a flag could be added to change which colors are used where?

Here is what it looks like for me:

![image](https://user-images.githubusercontent.com/25432/209214078-c7376d58-3f6b-432e-a40e-54831b2c5d6f.png)

The terminal's configuration how it will display the color, `green` for example, will change the result.
